### ISSUE TITLE
Specify a formatting style.

### ISSUE THREAD

**Issue by RobertBaruch** [JohnDMcMaster/open-tl866#55]
Specify a style to be used for formatting C and Python files. Inconsistent styles lead to excessive or unnecessary changes in diffs (especially when using IDEs with autoformatters), and lead to poor readability.

Many IDEs support autoformatting with standard styles.

Suggestion: yapf for Python, Google clang-format for C.

**Comment by JohnDMcMaster** [comment]
@pdietl you made some progress on this?

**Comment by pdietl** [comment]
Python formatting was added with commit 88852fb8977e80d636247fc0be6f3753fd392cc2
and C formatting was added with #92

**Comment by JohnDMcMaster** [comment]
Ok sounds like this is fixed then, but please reopen and/or new issue if still needs attention
