### ISSUE TITLE
Compilation impossible

### ISSUE THREAD

**Issue by Giants92** [JohnDMcMaster/open-tl866#85]
Linux debian 5.10.0-14-686 #1 SMP Debian 5.10.113-1 (2022-04-29) i686 GNU/Linux
Try with : xc8-v1.45-full-install-linux-installer.run  and xc8-v2.00-full-install-linux-installer.run
Compilation (make) don't work.
Depending of the xc8 version installed but don't work.
With 2.00 => 
/usr/local/src/open-tl866/firmware/modes/epromv/main.c:126:6: error: variable has incomplete type 'void'
/usr/local/src/open-tl866/firmware/modes/epromv/main.c:126:15: error: expected ';' after top level declarator

With 1.45, different but don't compil.

Try with anoter linux distrib : Linux nas 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
and with 1.45 or 2.25 xc8 version
Same... compilation impossible.

 With 1.45 -->
   576:         #error "Your architecture is not supported"
                                                          ^ (103) #error: "Your architecture is not supported"
(100) unterminated #if[n][def] block from line 27
(908) exit status = 1
(908) exit status = 1
make[2]: *** [CMakeFiles/tl866-epromv.dir/build.make:206: CMakeFiles/tl866-epromv.dir/external/m-stack/usb/src/usb.c.p1] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/tl866-epromv.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

etc, etc...

Try also compilation bitbang, same...

**Comment by JohnDMcMaster** [comment]
Hi there,
Finally got a chance to look at this. You are using the 2.x compiler which is not supported per the readme:

```
The XC8 compiler from Microchip is used to compile our C code. Currently version 1.x is required. [Download it from Microchip's site](http://www.microchip.com/development-tools/pic-and-dspic-downloads-archive) and install it. When activating, select the Free version.
```

Please use the 1.x compiler. Hope that solves your issue!
